### ISSUE TITLE
Charts open with Humidity selected and display 'Error: No data...'

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#11]
When I click on a device the chart defaults to trying to display Humidity which causes an error mesage to appear since most devices don't record Humidity. Clicking on a device which does record humidity is fine,

The dialog message,  should be reworded to something like "No data has been recorded for this chart tab. Try clicking on another tab". 

It isn't really an error message anyway - it's more of an information thing.
![image](https://user-images.githubusercontent.com/15849181/53117786-96c3b500-3543-11e9-8117-7ec1597afa7f.png)

**Comment by sbrl** [comment]
Yep! This is because that sensor has apparently reported some humidity data in the past, which the system has picked up on. Said data probably needs cleaning out, as it's probably been assigned to the wrong device id by mistake by a previous iteration of the broker script.

**Comment by bsimmo** [comment]
Could it default to PM2.5 (since that's the main target at the moment, then move to Temperature, then .. if not recent data)
or possibly look at most recent data and then decide ?

**Comment by bsimmo** [comment]
Actually this seems better now.
it is defaulting to PM2.5 though with robin05 with no PM sensor it errors at start.

**Comment by BNNorman** [comment]
If you click on Robin05’s 1 year tab it thinks there something so I think it’s the old clean up routine that is required. I have some rubbish in my records which cause problems – just haven’t gotten around to removing it (have tested the SQL on my test machine and it worked – just looking for the bottle..)

**Comment by sbrl** [comment]
@bsimmo Ah yes - I fixed a bug in which it was defaulting to the first item it found, which is humidity. It was left over from the schema update.

**Comment by sbrl** [comment]
@BNNorman, can we close this now?

**Comment by BNNorman** [comment]
Yes I think so
