### ISSUE TITLE
Add a 'latest' call to the API

### ISSUE THREAD

**Issue by leftcase** [ConnectedHumber/Air-Quality-Web#14]
Currently fetching data from the API requires a `datetime` parameter to be passed to specify the date and time for which readings are required. It would be cool if we could pass a `latest` parameter instead which retrieves the latest readings from sensors.

Something like this for instance `https://aq.connectedhumber.org/api.php?action=fetch-data&latest&reading_type=PM25` would provide the most recent reading for each sensor.

**Comment by sbrl** [comment]
Hrm. Good idea! I opened a similar issue against _Laminar_, my continuous integration server, recently.

I could certainly add something like this:

```
https://aq.connectedhumber.org/api.php?action=fetch-data&datetime=latest&reading_type=PM25
```

**Comment by sbrl** [comment]
I've done some investigating, and it looks like I support this already! Try this:

```
https://aq.connectedhumber.org/api.php?action=fetch-data&datetime=now&reading_type=PM25
```
