### ISSUE TITLE
Non-linear x-axis, it should be linear for 'time'

### ISSUE THREAD

**Issue by bsimmo** [ConnectedHumber/Air-Quality-Web#15]
I've noticed that the x-axis in not locked to be linear, even though time tends to be.
So if data is missed, the axis can become compressed at that particular point (look at ben_pi01 for e.g. 24/02/19 before 12:00hr - 25/02/19 after 15:30hrs)

with MQTT data points can be missed, so these have to be accounted for as 'missed' and either left blank, or just let the line of fit do it's magic without it.  The axis should remain linear throughout the time period specified.

Hope that helps.

**Comment by sbrl** [comment]
Hrm, interesting! I hadn't noticed this myself. I think I've managed to fix it.

Does that look better to you?

![selection_136](https://user-images.githubusercontent.com/9929737/53439568-32e53480-39fa-11e9-994a-efea5692f68a.png)

**Comment by bsimmo** [comment]
Yes it does, plus I can see when no data was sent.

**Comment by sbrl** [comment]
Excellent! I'll close this as fixed then.

**Comment by bsimmo** [comment]
Actually, this isn't quite fixed, it needs to be done for all graph ranges. 
I  was looking at the 1 hour graph for mine just now as there is a data-point missing (the microwave was in use) and noticed it was compressed where that datapoint was.
So just set it linear time for any range selected, given.

**Comment by sbrl** [comment]
It should already be set for any range. Are some ranges working and not others, @bsimmo?
