### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#18]
Made some progress. Built the code in the home folder first then copied it to /var/www/html.

chown -R www-data:www-data is best done AFTER running the build commands. I found doing that created the required data folders (albeit with some warning about circular links - and something about a leaflet dependency that should be manually installed - no I don't know what it was.

The notes on denying access for nginx and apache need to be clarified. In apache the file should be called .htaccess. In nginx you have to edit /etc/nginx/sites-available/default (or if using a virtual site edit the file belonging to that site).

I will go through all this one more time from scratch.

**Comment by BNNorman** [comment]
Totally fresh install ./build client throws an error:-

*packaging Javascript
./build line 152: node_modules/rollup/bin/rollup: no such file or directory

The node_modules folder does not contain a rollup folder at this point and only contains 14 sub folders (my other system has loads more). 

I will stop installing till I hear from you.

**Comment by BNNorman** [comment]
Hey up. Found some messages whuich had scrolled off the screen during ./build setup setup-dev

**Comment by BNNorman** [comment]
reverted to using buster for php7.3 and added mbstring to the install list but ./build setup setup-dev throws this warning
leaflet.marckercluster1.4.1 requires a peer of leaflet@~1.3.1 but none installed

./build client now works though it does list a load of circular dependencies in node_modules - can these be ignored?

**Comment by BNNorman** [comment]
The map now comes up but I don't get any pins (leflet.markercluster issue I guess). Also still get the invalid JSON < character we discussed at the meetup.

**Comment by sbrl** [comment]
> leaflet.marckercluster1.4.1 requires a peer of leaflet@~1.3.1 but none installed

Yep, you can ignore this warning.

> ./build client now works though it does list a load of circular dependencies in node_modules - can these be ignored?

Yeah, you can ignore these too. It's the Chart.js dependency being badly packaged causing that issue.

> ./build client now works though it does list a load of circular dependencies in node_modules - can these be ignored?

What messages were those?

> chown -R www-data:www-data is best done AFTER running the build commands

Oh, yeah! That's a great point. I'll update the instructions. The build script needs write access to the build folder in order to work. On the production server I do `sudo -u www-data NODE_ENV=production ./build client`.

> The notes on denying access for nginx and apache need to be clarified. In apache the file should be called .htaccess. In nginx you have to edit /etc/nginx/sites-available/default (or if using a virtual site edit the file belonging to that site).

Indeed. I'll investigate clarifying that a bit.

**Comment by sbrl** [comment]
- Instructions: reordered
 - `data/` directory web server configuration: clarified (I don't know what I was thinking when I was writing that. I think I must have been tired - Thursday _was_ a long day.....)
 - Added additional check to avoid issues whereby people don't clone the repository with git
 - Added additional check to avoid issues whereby the repository directory is not writeable

**Comment by BNNorman** [comment]
Clearly, you build directly within the /var/www/html folder - I take a more cautious approach building outside then copying the files and setting their ownerships

Circulare dependencies:-

client_src/js/index.mjs → app/app.js...
(!) postcss plugin: The onwrite hook used by plugin postcss is deprecated. The generateBundle hook should be used instead.
(!) Circular dependency: node_modules/moment/src/lib/create/from-anything.js -> node_modules/moment/src/lib/create/valid.js -> node_modules/moment/src/lib/create/utc.js -> node_modules/moment/src/lib/create/from-anything.js
(!) Circular dependency: node_modules/moment/src/lib/units/month.js -> node_modules/moment/src/lib/moment/get-set.js -> node_modules/moment/src/lib/units/month.js
(!) Circular dependency: node_modules/moment/src/lib/moment/get-set.js -> node_modules/moment/src/lib/units/year.js -> node_modules/moment/src/lib/moment/get-set.js
(!) Circular dependency: node_modules/moment/src/lib/create/local.js -> node_modules/moment/src/lib/create/from-anything.js -> node_modules/moment/src/lib/locale/locales.js -> node_modules/moment/src/lib/locale/base-config.js -> node_modules/moment/src/lib/units/week.js -> node_modules/moment/src/lib/create/local.js
(!) Circular dependency: node_modules/moment/src/lib/create/local.js -> node_modules/moment/src/lib/create/from-anything.js -> node_modules/moment/src/lib/locale/locales.js -> node_modules/moment/src/lib/locale/base-config.js -> node_modules/moment/src/lib/units/week.js -> node_modules/moment/src/lib/units/week-calendar-utils.js -> node_modules/moment/src/lib/create/local.js
(!) Circular dependency: node_modules/moment/src/lib/create/from-string-and-format.js -> node_modules/moment/src/lib/create/from-string.js -> node_modules/moment/src/lib/create/from-string-and-format.js
(!) Circular dependency: node_modules/moment/src/lib/create/local.js -> node_modules/moment/src/lib/create/from-anything.js -> node_modules/moment/src/lib/create/from-string-and-array.js -> node_modules/moment/src/lib/create/from-string-and-format.js -> node_modules/moment/src/lib/create/from-string.js -> node_modules/moment/src/lib/create/from-array.js -> node_modules/moment/src/lib/create/local.js
(!) Circular dependency: node_modules/moment/src/lib/duration/constructor.js -> node_modules/moment/src/lib/duration/valid.js -> node_modules/moment/src/lib/duration/constructor.js
(!) Circular dependency: node_modules/moment/src/lib/duration/create.js -> node_modules/moment/src/lib/duration/constructor.js -> node_modules/moment/src/lib/duration/valid.js -> node_modules/moment/src/lib/duration/create.js
(!) Circular dependency: node_modules/moment/src/lib/duration/create.js -> node_modules/moment/src/lib/units/offset.js -> node_modules/moment/src/lib/duration/create.js
(!) Circular dependency: node_modules/moment/src/lib/moment/add-subtract.js -> node_modules/moment/src/lib/duration/create.js -> node_modules/moment/src/lib/units/offset.js -> node_modules/moment/src/lib/moment/add-subtract.js
created app/app.js in 19.3s

**Comment by BNNorman** [comment]
I think my map display problems are due to the NGINX php config in sites-available/default. I tried un commenting the location /.php section but (using webget) I get this  page returned - error message highlighted near end.

I don't recollect having to change anything on apache (might have been done for me with an apt install somewhere along the line.

'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  
**<p>The requested URL <code>/api.php</code> was not found on this server.** 
<ins>That\xe2\x80\x99s all we know.</ins>\n'

**Comment by sbrl** [comment]
Hrm. I could certainly investigate refactoring so that you serve a subdirectory of the repository instead via the web server - I've seen FreshRSS do that.

You can ignore the circular references.

Could you paste your Nginx config here please? Sounds like a bug in it to me. Might be able to draft an example one from your version if you like

**Comment by BNNorman** [comment]
Here you go. Also access.log and error.log. 

[info.txt](https://github.com/ConnectedHumber/Air-Quality-Web/files/2955740/info.txt)

**Comment by BNNorman** [comment]
Sorted. Some fairy put a semi colon at the end of the password line in data/setting.toml. It's working now.
That's the problem when mixing languages in daily life.

**Comment by sbrl** [comment]
Cool, glad you could get it sorted! :smiley_cat:
