### ISSUE TITLE
README, INSTALL & API Documentation

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#19]
I think these should be three separate documents - easier to maintain and read.

**Comment by sbrl** [comment]
Great idea!

**Comment by sbrl** [comment]
The new docs are live! I've written a new documentation generator called [nightdocs](https://gitlab.com/sbrl/nightdocs/), because I couldn't get _docpress_ to work.

**Comment by sbrl** [comment]
Check them out here:

https://aq.connectedhumber.org/__nightdocs/00-Welcome.html
