### ISSUE TITLE
Node names not updated

### ISSUE THREAD

**Issue by robinharris** [ConnectedHumber/Air-Quality-Web#21]
Brian02, brian02 and brian04 have changed their names to the new standard but the old names are appearing in the pop up boxes.

**Comment by BNNorman** [comment]
It's got to be cacheing - they are correct when I access the map.

**Comment by robinharris** [comment]
You are correct Brian.  Will close.

**Comment by robinharris** [comment]
Just a local caching issue.

**Comment by sbrl** [comment]
Cool, glad you were able to fix it! Sometimes CTRL + SHIFT + R fixes it, other times you have to clear your browser cache.
