### ISSUE TITLE
API enhancement

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#22]
I'm using the API to detect new devices and add them to my dev copy of the database.
I can get a list of all devices and the device_types info as a combined json BUT to be able to update my local database I need two separate calls:-

list-devices - add an option to return the raw devices table
device-id    - add an option to return the raw device_types

I don't care if this is, instead, done with new actions like device-table,device-types-table

Having the raw tables means I can compare local to server and add new entries/remove old thus keeping our copies in sync (we don't care about the readings etc - we run subscriber scripts to capture that but it rejects unknown devices (because the database doesn't have .the requied information.

I'd have a go at writing new actions myself but I haven't gotten my head around your code as it is just yet. Also, thought you'd be able to do it a lot quicker. :-)

**Comment by BNNorman** [comment]
I managed to add device_type to the output for list-devices & device-info by editing MariaDBDeviceRepository.php (here at home). So that's easy enough. Might have a dabble at adding an extra action to send back the device_types table

**Comment by BNNorman** [comment]
Ok. Got stuck - api.php returns 404 Not found.

Created Actions\DeviceTypes.php (just a copy of DeviceInfo.php with minor changes in handle() at line 48 & 54
Added public function get_device_types(); to IDeviceRepository.php
Added public function get_device_types() to end of MariaDBDeviceRepository.php 

This isn't complete. Just supposed to return a list of device_typesIDs for testing.

So, what have I missed


 public function get_device_types() {

                $s=$this->get_static;

                $query_result=$this->database->query(
                        "SELECT 
						{($s("table_name_type")}.{$s("column_type_id")} from {$s("table_name_type")};"
                        )->fetchAll();
                $result=[];
                foreach($query_result as $key=>$value){
                        $result[strtolower($key)]=$value;
                        }
                return  $result;
        }

**Comment by BNNorman** [comment]
I see you've already added the altitude. So, I think you just need to add the device_types id into the output from get_device_info_ext - would that just be a case of removing the if $key==$column_type_id .. continue bit?

**Comment by sbrl** [comment]
Altitude is already done in #23.

I'm somewhat wary of adding type_id, as the use-case seems to be rather specific (and I don't actually output the types themselves elsewhere that would make such information useful), but I've added device_type_id as `type_id` in `list-devices` for you, and deployed that as 0.5.4.1.

**Comment by sbrl** [comment]
I'd probably recommend a `mysqldump` / replication based system though if you're wanting to copy the contents of a table from 1 DB to another though.

**Comment by BNNorman** [comment]
Always possible but requires a lot of steps: login to serdump transfer file to pc drop device source the dump

**Comment by sbrl** [comment]
Ah, I see!
Is it working now for you? If so, I'll close this issue.

**Comment by BNNorman** [comment]
no. I've got altitude.
But when I edit get device info and comment out this bit:-
``` 
if($key == self::$column_type_id)
       continue;
```
The I get the device_type key - which is what I need to make my planned code work.

BTW - the builds ran a lot smoother - (apart from circular reference still)

**Comment by sbrl** [comment]
Hrm. Strange. Does it work for you on the production server? I implemented support on the `list-devices` action only for `type_id`.

**Comment by sbrl** [comment]
e.g. https://aq.connectedhumber.org/api.php?action=list-devices works for me

**Comment by BNNorman** [comment]
Yes it does -Sorry, I was expecting it in in device-info. Just need to change my code.
