### ISSUE TITLE
Unexpected zoom clicking the Cottingham sensors

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#25]
When click on the number in Robin's heat map in Cottingham the screen zooms in, massively to street level, and is all green.

If I zoom out slightly it sorts itself out.

I suspect this is due to the close proximity of several sensors in that area - the heat maps overlap.

**Comment by sbrl** [comment]
Indeed. I'm using a plugin called _[leaflet.markercluster](https://www.npmjs.com/package/leaflet.markercluster)_, which handles all of this automatically.

Apparently there's an option that disables the automagic zoom completely. Not sure if we want to completely disable it though. Would it be worth a try?

**Comment by BNNorman** [comment]
Have you seen the behaviour?

What is the option? I can try it on my machine here to see what happens.

**Comment by sbrl** [comment]
Hello! Oops! I think I forgot to publish the changes production.

**Comment by sbrl** [comment]
Done.
