### ISSUE TITLE
New device - no message about no data

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#28]
Just added a new device - should sort itself out in 6 minutes - but when I opened the chart to check it all I got was a spinning thingy. It didn't display a 'no data' message.

**Comment by sbrl** [comment]
Ah, I see. It looks like an exception is being thrown in the console:

```
uncaught exception: Error: No types are currently present in the system.
```

Looks like it's just because it doesn't have any data in the DB associated with it yet.

I've pushed a fix which should get deployed in the next 1/2 hour.
