### ISSUE TITLE
Blob colour seems to be very unresponsive to PM2.5 level changes.

### ISSUE THREAD

**Issue by robinharris** [ConnectedHumber/Air-Quality-Web#31]
When PM2.5 levels on several devices are in the 30 - 40 range the heat blows remain green but the DEFRA scale suggests they should be yellow.  I don't recall every having seen anything other than green (apart from Brian's 3 devices in one location).  I know that PM2.5 levels have been way above the green band many times so it now strikes me as 'wrong' that the map only ever displays green.  Even if I increase the size of the blob, it remains green.

I can see yellow occasionally if two blobs start to merge but this is a different matter.

**Comment by sbrl** [comment]
I see. This does sound like a bug - I probably need to tweak the gradient colours to match up better.

**Comment by sbrl** [comment]
Ok, so I've added a gauge to the side of the map. The colours on the gauge correspond directly to the colours on the heatmap. The question now is whether the values on the gauge are correct according to the spec.

**Comment by BNNorman** [comment]
I like the scale except I would expect high values to be at the top not bottom

**Comment by sbrl** [comment]
Done, @BNNorman :smiley_cat: 

Looks like my build system got confused, so the update wasn't deployed. I'm going to investigate some cache-busting soon I think, so it should react to changes faster in your browser when I push a new version.

**Comment by BNNorman** [comment]
Magic - Moments - Works a treat
