### ISSUE TITLE
Default Heat Blob Radius too large

### ISSUE THREAD

**Issue by leftcase** [ConnectedHumber/Air-Quality-Web#4]
The default heat blob radius is rather large and (to a user without knowledge of the project) could indicate that the air quality of an extremely large area is being measured. When other sensors are added to the map, it may also create lots of clutter and overlap. Is it worth reducing the default heat blob radius to something smaller like 0.002?

**Comment by sbrl** [comment]
Yeah, we can reduce the default heat blob size. However, I've got it set to a large value to start with, as if 2 blobs are next to each other, they merge nicely to create a proper heatmap - they don't overlap.

Personally, I'd suggest that we keep the current size for now until we get more sensors - and then we can reduce the default size later (it's only a 1-line change!).

What do you think?

**Comment by leftcase** [comment]
Sounds sensible. As we get more nodes online we can reduce the size :-)

**Comment by sbrl** [comment]
I'll close this for now - and I'll patch as necessary when we get more nodes.
