### ISSUE TITLE
Setup a beta testing version

### ISSUE THREAD

**Issue by sbrl** [ConnectedHumber/Air-Quality-Web#40]
We should setup a beta testing version of this web interface that runs the very latest from the `dev` branch.

Much of the work to do this has already been completed (you can see the WIP [here](https://aq.connectedhumber.org/beta/), but currently we're getting an error in the logs:

```
[Thu Jul 18 23:58:43.107039 2019] [php7:error] [pid 3052] PHP Fatal error:  Uncaught Yosymfony\\Toml\\Exception\\ParseException: File "data/settings.toml" cannot be read. in /home/ci/sftp-root/Air-Quality-Web-Beta/www/vendor/yosymfony/toml/src/Toml.php:80\nStack trace:\n#0 /home/ci/sftp-root/Air-Quality-Web-Beta/www/lib/SBRL/TomlConfig.php(62): Yosymfony\\Toml\\Toml::parseFile('data/settings.t...', true)\n#1 /home/ci/sftp-root/Air-Quality-Web-Beta/www/api.php(23): SBRL\\TomlConfig->__construct('data/settings.t...', 'settings.defaul...')\n#2 {main}\n  thrown in /home/ci/sftp-root/Air-Quality-Web-Beta/www/vendor/yosymfony/toml/src/Toml.php on line 80
```

I've had this before when setting up the production version, but I can't for the life of me remember what the solution was right now. I'll have to think on it and come back to it.

It probably doesn't help that we're dealing with multiple levels of symbolic links, which are probably complicating matters somewhat here.

**Comment by sbrl** [comment]
Once it's setup, we'll want to add a "try the beta!" button.

We'll also want to  make sure that the `localStorage` values for the beta don't clash with the production version.

**Comment by BNNorman** [comment]
Clearly the error is a permissions thing. (File "data/settings.toml" cannot be read.)

Not sure about try the beta button - makes it easier to get too but since the interface is public would you want, potentially, 100s of hits throwing up potential errors? Perhaps just message @channel, when a new beta is available, with a link.

**Comment by robinharris** [comment]
Definitely should have a beta site but like Brian, think it's address should be invisible and given only to the people we want to invite.  No security required but no encouragement for lots of people to try something before it is reasonably tested.  The location we are discussing is more like an alpha test than a beta.  Who knows - we maybe need both.

**Comment by BNNorman** [comment]
I had similar thoughts re-alpha/beta they can share the same database.

**Comment by sbrl** [comment]
Hmmm, perhaps.

Yeah, really I mainly opened this issue at all because it was late last night and I wanted to go to bed, but also wanted to note the error message down for later pondering :P

**Comment by sbrl** [comment]
And fixed! The new beta version is now live over here:

https://aq.connectedhumber.org/beta/

**Comment by BNNorman** [comment]
I assume this is using the live database at the moment.

**Comment by sbrl** [comment]
Indeed it is, @BNNorman. We should open another issue about a testing DB I think.

A staged rollout is the best approach I think.
