### ISSUE TITLE
Beta - new sensor list question

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#41]
Although a single line is ok for a short list does it become scrollable if the list is longer?

**Comment by sbrl** [comment]
Oh, good question! If a sensor has a long description, it should wrap onto the next line. If not, then that's a bug.

If there are lots of sensors, then I think the popup box size will keep growing. I should probably make it scroll after a point.

Of course, the only way to truly know is to test it :P

**Comment by sbrl** [comment]
Closing this issue, since it's been open for a while and there doesn't appear to be anything I can do here.

Feel free to comment if you think otherwise and I'll re-open.
