### ISSUE TITLE
When clicking on a nice using a mobile device the pop up flashes open and close straight away

### ISSUE THREAD

**Issue by adamjennison** [ConnectedHumber/Air-Quality-Web#43]
I'm using an Android device with stock Google Chrome.
Click on any node and the pop up opens up then close straight away. No data is shown.

When choosing 'desktop' mode the pop ups open and display data normally.

This has also been reported to me by another user using Android. He also tried desktop mode with similar positive results.

Give me a shout on mattermost if you want more info.
:-)

**Comment by sbrl** [comment]
Hey, @adamjennison!

Indeed, there are several glaring issues with mobile support at the moment. Unfortunately, I have not yet had time to get around to implementing mobile support - though I plan to do so soon (see #45, a new tracking issue I've opened).

Until then, I'm going to close this issue - as mobile support isn't yet a thing.
