### ISSUE TITLE
Info on signin page

### ISSUE THREAD

**Issue by CrazyRobMiles** [ConnectedHumber/Air-Quality-Web#44]
I think it would be useful to add a message to our site that makes it clear where or readings come from. How about:

"The data displayed has been produced by low-cost devices developed by Connected Humber members as part of a community driven effort to build a network of smart sensors in the Humber Region"

We could add this to the changes pop-up that people see when the first hit the site.

**Comment by sbrl** [comment]
Sounds great!

Adding to the changelog dialog box is particularly easy - it's just a markdown file that's rendered: https://github.com/ConnectedHumber/Air-Quality-Web/blob/master/Changelog.md

Would you like to edit it and send a pull request, or shall I do it?

**Comment by CrazyRobMiles** [comment]
I've made the changes and sent a pull request.

**Comment by sbrl** [comment]
Thanks! I've merged the PR :D
