### ISSUE TITLE
Migration: Slow HTTP API calls

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#49]
Is the new server an issue?

**Comment by sbrl** [comment]
Hrm. Looks like it's taking ~6.9s (!) for the `api.php?action=list-reading-types&device-id=32` HTTP API call. Did the indexes make it over to the new DB server? They make a significant difference to the performance.

**Comment by BNNorman** [comment]
It was created from a mysqldump as before - that should create all the indexes.

**Comment by sbrl** [comment]
Hrm, that's really strange then. Nothing appears to have changed, perhaps we'll have to do some more `EXPLAIN`ing.... ugh.

**Comment by BNNorman** [comment]
What do we know about the server hardwares?

**Comment by BNNorman** [comment]
Interestingly its very quick on my android tablet. Possibly this is a browser issue or just my windows pc. Ill try with my windows laptop later.

**Comment by BNNorman** [comment]
Still slow on my PC - tried several browsers those that worked (Firefox, Chrome) were slow to load the charts. Those that didn't work (e.g. opera, chromium, Internet Explorer) hung on the circles at the start.

Odd that my tablet (Silk browser) was quick.

**Comment by BNNorman** [comment]
Hmm, clear recent history in the Firefox browser seems to have made it more responsive. (For now)

**Comment by sbrl** [comment]
Hrm, well, the new server has the following specs:

 - CPU: Intel Xeon E5-2673 v4 @ 2.30GHz
 - RAM: 8GiB
 - Disk: 30GiB

I don't have access to the old database server directly, so unfortunately I can't get the specs of it to compare with. The issue will absolutely be database query processing related.

Something that we'll have to keep an eye on, I guess. Should we close this issue for now?

**Comment by BNNorman** [comment]
My browser is still responsive since clearing the history.
