### ISSUE TITLE
Map Panel Buttons When No data

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#5]
When opening the data page buttons appear when there is no data. If it is the default view it gives the impression that there's no data at all.

Buttons with no data should either not be there or greyed out.

When the panel opens it should always default to one view where data is available.

**Comment by sbrl** [comment]
Excellent ideas! I'll look at implementing this when I next get a moment.

**Comment by sbrl** [comment]
Fixed!

 - I've swapped out the tab engine to use a library, so the device graph is shown by default.
 - The buttons for measurement types that are not reported by a device are now hidden.
