### ISSUE TITLE
When clicking sensors on the AQ Map (sometimes) the map just zooms

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#50]
I'm seeing this clicking on sensors marker and it appears intermittent or has a mind of it's own.

It's almost like the API thinks I've double-clicked the background. 

Perhaps this is a default action or an unintended  fall through in a case statement? The default should be do nothing if within a given radius of a marker since the user intended to click the marker but may have missed by a pixel or two.

**Comment by sbrl** [comment]
Hrm, this is a tricky one. It's likely to have something to do with the events in leaflet. The [documentation](https://leafletjs.com/reference-1.5.0.html#marker) details a few options that we can play around with.

I'm not entirely sure how to go about tackling this one. For me, it only zooms if I double-click. It's worth noting that even a significant delay of ~0.4s can result in a double click in my testing - this is a browser and operating system-specific setting that we don't have much control over as far as I know, unfortunately.

**Comment by BNNorman** [comment]
Hmm. I take your point.

**Comment by sbrl** [comment]
I'd be interested to know if this happens on multiple computers for you. Perhaps we can gain some more information that way.

**Comment by BNNorman** [comment]
Ok, i was using firefox. On my tablet it doesnt appear to do it with the silk browser. Ill try some other browsers later, been out all day.

**Comment by BNNorman** [comment]
Tried to repeat with firefox on PC - won't do it now so it's calling me a liar and I'll close the issue.
