### ISSUE TITLE
Mosquitto stuck Address in use (1883)

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#53]
URGENT: I tried systemctl stop mosquitto and restart but always comes up address in use

**Comment by BNNorman** [comment]
Forget that - it's kicked in now.

**Comment by sbrl** [comment]
Fixed it - there was a zombie process lying around that had grabbed the port. I killed ti and restarted the service.

Note that it is NOT the `mosquitto` service you want. I disabled that one on purpose - it's `mosquitto-broker` that you want instead @BNNorman.

We should probably document this somewhere.

**Comment by BNNorman** [comment]
I'll try to remember that. Expo kit working well today.
