### ISSUE TITLE
Issue with web site on some devices

### ISSUE THREAD

**Issue by CrazyRobMiles** [ConnectedHumber/Air-Quality-Web#55]
The map seems to be locking up for some users. Works OK for me on Chrome but locks up with a greyed out display on IE and Safari.

![image](https://user-images.githubusercontent.com/3390641/67471653-a69e1680-f647-11e9-951b-56cdc34abfd7.png)

**Comment by CrazyRobMiles** [comment]
It looks like it might be this: 
![image](https://user-images.githubusercontent.com/3390641/67472308-d0a40880-f648-11e9-9c39-cb1c8730d810.png)
The message doesn't appear on a working load.

**Comment by CrazyRobMiles** [comment]
Ha. Ignore that. Just done a reload on the working page and it worked fine, with that error. I've had a look at the code and it is just a sensible error message.

**Comment by CrazyRobMiles** [comment]
Tried some different machines and it works OK on them. Maybe an issue with cookies and the migratin of the url to sensors

**Comment by bsimmo** [comment]
This happens on all of mine, different browser different devices.
theat little box is
_tippy-tooltip_
it does not go away and close itself.

Everything loads in the background, but it's not usable.

I think it happened with the most recent update (1.3 or the sensor header change)

**Comment by BNNorman** [comment]
Works ok on my amazon tablet with Silk browser. Though theres a significant lag between opening a chart and the graph appearing.

**Comment by sbrl** [comment]
Hey! That looks like the first-run tutorial isn't working correctly. The null cell polygons don't really any thing to do with that bit of the code.

Very strange. Which browsers is this in @CrazyRobMiles & @bsimmo? If it's an issue, we might just have to disable the first-run tutorial.

**Comment by CrazyRobMiles** [comment]
I'm not sure if it is a browser thing. I think it is more likely that it uses a cookie to determine if it has displayed or not and gets stuck on devices where it hasn't been displayed. Could the change of url affected where it stores the cookie for the first run tutorial? (or am I just completely misunderstanding how it works?)

**Comment by CrazyRobMiles** [comment]
The first run tutorial is a nice thing to have, but I think we can do without it if it is the cause of the problem.

**Comment by BNNorman** [comment]
Tge cookie idea is easy to test. Perhaps ben could flush his out and retry?

**Comment by bsimmo** [comment]
Already flushed out all the browsers before I posted, happens on chrome,
edge and edge-chrome.
Mobile and mobile (desktop) and Win10.
AQ... and Sensors...



Disable the tutorial for now, test on the beta site to get it to work.
See if that is the problem.

Why it has stopped working, I don't know.

**Comment by BNNorman** [comment]
Hmm, i think you need to bring a failing device to the next meetup otherwise its a lot of guesswork.

**Comment by bsimmo** [comment]
It is but it needs to be working now.

Bug fix it later on the beta site.

Can't bring the PC :-( and the mobile is just Android 9 with up to date
browsers.
I could bring the laptop, but it's a school laptop, uses just Edge and is
locked down of course.

The best I could do above was tell you the module/function the box was from
via the dev tools.

And it worked fine before when the title was Air Quality (or whatever it
used to say). It could be a chrome/chromium/EdgeHtml change but doubt all
three engines had similar changes on two platforms.

One thing I didn't test (yet) is if I actually go through the full
introduction as I just hit cancel each time.

If there is any other logging I can do on the PC?

Not sure how to enable Dev tools etc on Android.

If we're lucky it may just go away.

**Comment by CrazyRobMiles** [comment]
I’ve seen this problem on my devices. I  think we should move the tutorial behind a button so that we can test it.

**Comment by bsimmo** [comment]
Just looked at this on my PC again.
For now you can hit **ESC** to **bypass** the _failing_ tutorial* (the small rectangular box (Chrome/Edge)

For mobile (Android anyway) devices I would suggest not using it or showing it to anyone for now


(*assuming it is that)

**Comment by sbrl** [comment]
Whether the tutorial is launched or not is actually checked by using a localStorage key, not a cookie. This is done here:

https://github.com/ConnectedHumber/Air-Quality-Web/blob/dev/client_src/js/Tour.mjs#L141-L154

I could certainly put it behind a button. Let's try that.

**Comment by sbrl** [comment]
Fixed it. Turns out there was a change in the API in a recent update of Shepard.js, which is used for the tour. It should now be working on the beta version in ~10 minute .

**Comment by sbrl** [comment]
There, it should be deployed now. Don't forget to reload without cache with Ctrl + Shift + R.

If all works, then I'll release this to stable.

**Comment by sbrl** [comment]
Thanks for checking @BNNorman! Yeah, it is taking a while. It's because of the `last_seen` SQL query - it takes a long time on the dataset we've acquired lol.

Is there an index on `readings.s_or_r`? I think it might help.

**Comment by BNNorman** [comment]
Yes there is an index on s_or_r. Last seen would be max(s_or_r).

**Comment by sbrl** [comment]
Yeah, that's what it uses, @BNNorman. Hrm, might have to rethink that one :-/
