### ISSUE TITLE
API and documents not working

### ISSUE THREAD

**Issue by bsimmo** [ConnectedHumber/Air-Quality-Web#63]
Looking at the documentation and trying to use 
https://sensors.connectedhumber.org/app/api.php?action=list-devices&only-with-location=true

is not working

**Comment by sbrl** [comment]
Hrm. Something strange is going on here. Investigating.

**Comment by sbrl** [comment]
Fixed it - it was rogue SQL.

Also your URL is wrong there @bsimmo, you want to drop the `app/` there:

```
https://sensors.connectedhumber.org/api.php?action=list-devices&only-with-location=true
```

**Comment by sbrl** [comment]
The fix should be out in the next hour.
