### ISSUE TITLE
Wrong base URL in the API docs

### ISSUE THREAD

**Issue by adamjennison** [ConnectedHumber/Air-Quality-Web#69]
Found on https://sensors.connectedhumber.org/__nightdocs/05-API-Docs.html

The wording in the first sentence:
_On the main production instance, this can be found here._
The link from '_here_' points to https://aq.connectedhumber.org/api.php when it should be https://sensors.connectedhumber.org/api.php

**Comment by sbrl** [comment]
Thanks! Updated.
