### ISSUE TITLE
Issue #5 has re-appeared

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#7]
If you click on the top device in my cluster it opens on a no-data page.

**Comment by sbrl** [comment]
Hrm, I see! I think this might be related tot he database issue in #6.

I theorise that the system is assuming that data is available for PM25 when the relevant API call returns it in the list of supported measurement types.

Removing the redundant data from the system should take care of this.

**Comment by BNNorman** [comment]
Need to check if robin did that.

**Comment by BNNorman** [comment]
Actually your theory is faulty. If there's extra data why do i get a popup saying 'no data'. I theorise you have two sql statements one says there is data and the other says not.

**Comment by BNNorman** [comment]
Oddly, it's behaving this morning - you been fiddling?

**Comment by sbrl** [comment]
Nope! Haven't fiddled with it since the last message.

The query that returns the data itself looks only within the specified time-frame. The query that determines whether a given device actually has any data of a given measurement type associated with it does not have any restriction on time-frame.

**Comment by BNNorman** [comment]
Ok. Well what has happened is very odd unless tbe broker script thinks there's data. Sto?l need to talk to robin.

**Comment by BNNorman** [comment]
Found out why the problem disappeared again. Something has put pm values in for brian01 that should not be there. Robin and i are looking at the subscriber code. I suspect a global variable is responsible and that it happens when a new message arrives before a prior message has been fully dealt with.

**Comment by sbrl** [comment]
Cool! Sounds like we've found the issue. I'll transfer this issue over to the new MQTT repository.

**Comment by sbrl** [comment]
Oops! I don't appear to have admin privileges on the new repository, so I can't transfer it.

**Comment by BNNorman** [comment]
I'd wait. A new script is now in place and a newer one being written. I'll close this one.

**Comment by sbrl** [comment]
Ok. Thanks, @BNNorman!

**Comment by BNNorman** [comment]
I'll have a go at removing redundant dat
