### ISSUE TITLE
Blank Ok Dialog

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/Air-Quality-Web#8]
Appears when I open a device. If I click ok I can then select a tab to see data. Obviously a teething problem from the recent changes.

**Comment by BNNorman** [comment]
Pleased to see that my BME280 sensor device hasn';t got any rogue PM values :-) so that appears fixed

**Comment by sbrl** [comment]
I see. I think this is a duplicate of #9. Either way, it should be fixed now :P

We've still got the issue of the extra measurement types in the DB though.

Excellent! Glad we've managed to fix that one.
