### ISSUE TITLE
Initial opening of an AQ node shows a pop up notice - no data shown

### ISSUE THREAD

**Issue by adamjennison** [ConnectedHumber/Air-Quality-Web#9]
When clicking on a node it should default to a sensor reading - usually 2.5ppm but at the moment it seems there's no default so showing a pop up - no message is shown in the pop up, it's just blank.

Click ok to the pop up and then choose 2.5, 10, temp etc and the system works as normal..
:)

**Comment by sbrl** [comment]
Thanks! Looks like I missed updating a few actions in the API to the new database structure. Should be sorted soon :-)

**Comment by sbrl** [comment]
Fixed! Thanks for the report.
